### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by jonabantao** [jonabantao/munchables#1]
- [ ] Backend: DB, model, controller, views
- [ ] Redux Loop: ajax, actions, reducer
- [ ] Presentation Components
- [ ] Styling
- [ ] Smooth, bug-free navigation
- [ ] Adequate and appropriate seeds
- [ ] Demo login ability

**Comment by evhumphrey** [comment]
I would:
- [ ] Have some text on your `/` page that has the title of your page and a description on the photo
- [ ] Logo placeholder should say Munchables until a logo is ready (if you decide to design one), and vertically centered
- [ ] Links on navbar should be styled. (Looks like default styling). I suggest removing the underline, and adding a hover effect. I would also add padding on the left and right so they have a larger clickable area
- [ ] Make the signup background less transparent, so there is more transparent
- [ ] Navbar color looks a bit off to me. I suggest going with a more neutral color, or more intense color
- [ ] Buttons and inputs should be bigger
- [ ] You should use `NavLinks` for the Login and Logout in the navbar. These will automatically add the a class called `active` when the path matches the current location, which you can style.
- [ ] I would avoid styling the errors like they way you have them; it looks almost like a button.

My thoughts in picture form (a suggestion):
![screen shot 2018-01-31 at 7 06 54 pm](https://user-images.githubusercontent.com/6361824/35659268-2ff86860-06ba-11e8-9b03-8d5e35175af5.png)

**Comment by evhumphrey** [comment]
Let me know if you have any questions!

**Comment by jonabantao** [comment]
Will do. Will work on all of them except:

>  Make the signup background less transparent, so there is more transparent

...Not sure if I understood that one?

**Comment by evhumphrey** [comment]
Sorry about that comment, was a typo. 2 more minor things, then it should be good to go:
- [ ] Style logout button
- [ ] Hover styling for Login and Sign Up links in navbar

**Comment by evhumphrey** [comment]
Just checked it, looks good!
