### ISSUE TITLE
PA Review: Images and Videos in Project

### ISSUE THREAD

**Issue by jonabantao** [jonabantao/munchables#4]
- [ ] Backend: DB, model, controller, views
- [ ] Presentation Components
- [ ] Adequate and appropriate seeds
- [ ] All valid Youtube URLs are able to be shown on the recipe show page
- [ ] Images are able to be uploaded and saved in AWS

**Comment by evhumphrey** [comment]
Awesome! I would clean up design a bit: 

![screen shot 2018-02-06 at 4 40 24 pm](https://user-images.githubusercontent.com/6361824/35893705-2679ec9c-0b64-11e8-9e5f-44d0e18a437f.png)
![screen shot 2018-02-06 at 5 07 05 pm](https://user-images.githubusercontent.com/6361824/35893710-2886b178-0b64-11e8-97ca-356a53602602.png)
And do something similar for edit step

**Comment by evhumphrey** [comment]
Nice!
