### ISSUE TITLE
PA Review: Comments

### ISSUE THREAD

**Issue by jonabantao** [jonabantao/munchables#5]
- [ ] Backend: DB, model, controller, views
- [ ] Redux Loop: ajax, actions, reducer
- [ ] Presentation Components
- [ ] Styling
- [ ] Smooth, bug-free navigation
- [ ] Adequate and appropriate seeds
- [ ] Users will not be able to comment if logged in
- [ ] Comment timestamps

**Comment by evhumphrey** [comment]
👍
